export {
  PRIVACY_POLICY_ICON,
  PRIVACY_POLICY_INTRO,
  PRIVACY_POLICY_PAGE_DESCRIPTION,
  PRIVACY_POLICY_PAGE_SUBTITLE,
  PRIVACY_POLICY_PAGE_TITLE,
  PRIVACY_POLICY_ROUTE,
  PRIVACY_POLICY_SECTIONS,
  PRIVACY_POLICY_UPDATED_AT,
  PRIVACY_POLICY_UPDATED_PREFIX,
} from './constants';
