import type { Character } from './types';

/** Демонстрационный персонаж листа (волшебник 1-го уровня). */
export const DEMO_CHARACTER: Character = {
  id: 'demo-wizard',
  name: 'Персонаж',
  avatarUrl: null,
  species: null,
  className: 'Волшебник',
  background: null,
  level: 1,
  experience: { current: 0, nextLevel: 300 },
  inspiration: true,
  armorClass: {
    base: 10,
    ability: 'dexterity',
    natural: false,
  },
  speed: {
    values: {
      walk: 30,
      burrow: 0,
      climb: 0,
      fly: 0,
      swim: 0,
    },
    hover: false,
    unit: 'feet',
  },
  vision: {
    normal: 0,
    darkvision: 0,
    unit: 'feet',
  },
  abilities: {
    strength: 19,
    dexterity: 16,
    constitution: 13,
    intelligence: 10,
    wisdom: 10,
    charisma: 10,
  },
  savingThrowProficiencies: ['intelligence', 'wisdom'],
  skills: [
    { name: 'Акробатика', ability: 'dexterity', proficiency: 'none' },
    { name: 'Анализ', ability: 'intelligence', proficiency: 'expertise' },
    { name: 'Аркана', ability: 'intelligence', proficiency: 'none' },
    { name: 'Атлетика', ability: 'strength', proficiency: 'none' },
    { name: 'Внимательность', ability: 'wisdom', proficiency: 'half' },
    { name: 'Выживание', ability: 'wisdom', proficiency: 'proficient' },
    { name: 'Выступление', ability: 'charisma', proficiency: 'none' },
    { name: 'Запугивание', ability: 'charisma', proficiency: 'none' },
    { name: 'История', ability: 'intelligence', proficiency: 'none' },
    { name: 'Ловкость рук', ability: 'dexterity', proficiency: 'none' },
    { name: 'Медицина', ability: 'wisdom', proficiency: 'proficient' },
    { name: 'Обман', ability: 'charisma', proficiency: 'none' },
    { name: 'Природа', ability: 'intelligence', proficiency: 'proficient' },
    { name: 'Проницательность', ability: 'wisdom', proficiency: 'none' },
    { name: 'Религия', ability: 'intelligence', proficiency: 'none' },
    { name: 'Скрытность', ability: 'dexterity', proficiency: 'none' },
    { name: 'Убеждение', ability: 'charisma', proficiency: 'none' },
    { name: 'Уход за животными', ability: 'wisdom', proficiency: 'none' },
  ],
  health: { current: 7, max: 7, temporary: 0 },
  hitDice: [],
  extraHitDice: [],
  classResources: [],
  proficiencies: {
    armor: ['Стёганый доспех'],
    weapons: ['Всё простое оружие'],
    weaponMasteries: ['Кинжал'],
    tools: [],
    languages: ['Общий'],
  },
  currency: {
    copper: 0,
    silver: 0,
    electrum: 0,
    gold: 0,
    platinum: 0,
  },
  inventory: [
    {
      title: 'Оружие',
      items: [
        {
          id: 'club',
          name: 'Дубинка',
          category: 'Простое оружие',
          icon: 'tabler:sword',
          stats: [
            { label: 'Атака', value: '+6' },
            { label: 'Дробящий', value: '1к4+4' },
          ],
          quantity: 1,
          weight: 2,
          equipped: false,
        },
        {
          id: 'handaxe',
          name: 'Ручной топор',
          category: 'Простое оружие',
          icon: 'tabler:axe',
          stats: [
            { label: 'Атака', value: '+4' },
            { label: 'Рубящий', value: '1к6+4' },
          ],
          quantity: 1,
          weight: 2,
          equipped: false,
        },
      ],
    },
    {
      title: 'Экипировка',
      items: [
        {
          id: 'padded-armor',
          name: 'Стёганый доспех',
          category: 'Лёгкая броня',
          icon: 'tabler:shirt',
          stats: [{ label: 'КД', value: '11' }],
          quantity: 1,
          weight: 8,
          equipped: true,
        },
        {
          id: 'padded-armor-spare',
          name: 'Стёганый доспех',
          category: 'Лёгкая броня',
          icon: 'tabler:shirt',
          stats: [{ label: 'КД', value: '11' }],
          quantity: 1,
          weight: 8,
          equipped: false,
        },
        {
          id: 'plate-armor',
          name: 'Латный доспех +3',
          category: 'Тяжёлая броня',
          icon: 'tabler:shirt',
          stats: [{ label: 'КД', value: '21' }],
          quantity: 1,
          weight: 65,
          equipped: false,
        },
        {
          id: 'shield',
          name: 'Щит +3',
          category: 'Щит',
          icon: 'tabler:shield',
          stats: [{ label: 'КД', value: '5' }],
          quantity: 1,
          weight: 6,
          equipped: false,
        },
      ],
    },
    {
      title: 'Инструменты',
      items: [],
    },
  ],
};
