import type { Character } from './types';

/**
 * Пустой персонаж по умолчанию: характеристики 10, без владений, навыков и
 * прогресса.
 */
export const DEFAULT_CHARACTER: Character = {
  id: 'new-character',
  name: 'Персонаж',
  avatarUrl: null,
  species: null,
  size: null,
  features: [],
  spells: [],
  characterClass: null,
  background: null,
  level: 1,
  experience: { current: 0, nextLevel: 300 },
  inspiration: false,
  armorClass: {
    base: 10,
    ability: 'dexterity',
    natural: false,
  },
  speed: {
    values: {
      walk: 30,
      burrow: 0,
      climb: 0,
      fly: 0,
      swim: 0,
    },
    hover: false,
    unit: 'feet',
  },
  vision: {
    normal: 0,
    darkvision: 0,
    unit: 'feet',
  },
  abilities: {
    strength: 10,
    dexterity: 10,
    constitution: 10,
    intelligence: 10,
    wisdom: 10,
    charisma: 10,
  },
  savingThrowProficiencies: [],
  skills: [
    { name: 'Акробатика', ability: 'dexterity', proficiency: 'none' },
    { name: 'Анализ', ability: 'intelligence', proficiency: 'none' },
    { name: 'Аркана', ability: 'intelligence', proficiency: 'none' },
    { name: 'Атлетика', ability: 'strength', proficiency: 'none' },
    { name: 'Внимательность', ability: 'wisdom', proficiency: 'none' },
    { name: 'Выживание', ability: 'wisdom', proficiency: 'none' },
    { name: 'Выступление', ability: 'charisma', proficiency: 'none' },
    { name: 'Запугивание', ability: 'charisma', proficiency: 'none' },
    { name: 'История', ability: 'intelligence', proficiency: 'none' },
    { name: 'Ловкость рук', ability: 'dexterity', proficiency: 'none' },
    { name: 'Медицина', ability: 'wisdom', proficiency: 'none' },
    { name: 'Обман', ability: 'charisma', proficiency: 'none' },
    { name: 'Природа', ability: 'intelligence', proficiency: 'none' },
    { name: 'Проницательность', ability: 'wisdom', proficiency: 'none' },
    { name: 'Религия', ability: 'intelligence', proficiency: 'none' },
    { name: 'Скрытность', ability: 'dexterity', proficiency: 'none' },
    { name: 'Убеждение', ability: 'charisma', proficiency: 'none' },
    { name: 'Уход за животными', ability: 'wisdom', proficiency: 'none' },
  ],
  health: { current: 0, max: 0, temporary: 0 },
  hitDice: [],
  extraHitDice: [],
  classResources: [],
  proficiencies: {
    armor: [],
    weapons: [],
    weaponMasteries: [],
    tools: [],
    languages: [],
  },
  currency: {
    copper: 0,
    silver: 0,
    electrum: 0,
    gold: 0,
    platinum: 0,
  },
  inventory: [],
  notes: '',
};
