import type { Character } from './types';

import { DRAFT_CHARACTER_ID } from './constants';

/**
 * Пустой персонаж по умолчанию: характеристики 10, без владений, навыков и
 * прогресса.
 */
export const DEFAULT_CHARACTER: Character = {
  id: DRAFT_CHARACTER_ID,
  name: 'Персонаж',
  avatarUrl: null,
  species: null,
  size: null,
  features: [],
  spells: [],
  spellcasting: { ability: null, prepared: { custom: null, bonus: 0 } },
  spellSlots: [],
  characterClass: null,
  characterBackground: null,
  level: 1,
  experience: { current: 0, nextLevel: 300 },
  inspiration: false,
  armorClass: {
    base: 10,
    abilities: ['dexterity'],
    natural: false,
    dexLimit: null,
    custom: false,
  },
  speed: {
    values: {
      walk: 30,
      burrow: 0,
      climb: 0,
      fly: 0,
      swim: 0,
    },
    hover: false,
    unit: 'feet',
  },
  vision: {
    normal: 0,
    darkvision: 0,
    blindsight: 0,
    tremorsense: 0,
    truesight: 0,
    unit: 'feet',
  },
  abilities: {
    strength: 10,
    dexterity: 10,
    constitution: 10,
    intelligence: 10,
    wisdom: 10,
    charisma: 10,
  },
  savingThrowProficiencies: [],
  skills: [
    {
      name: 'Акробатика',
      ability: 'dexterity',
      proficiency: 'none',
      bonuses: [],
    },
    {
      name: 'Анализ',
      ability: 'intelligence',
      proficiency: 'none',
      bonuses: [],
    },
    {
      name: 'Аркана',
      ability: 'intelligence',
      proficiency: 'none',
      bonuses: [],
    },
    { name: 'Атлетика', ability: 'strength', proficiency: 'none', bonuses: [] },
    {
      name: 'Внимательность',
      ability: 'wisdom',
      proficiency: 'none',
      bonuses: [],
    },
    { name: 'Выживание', ability: 'wisdom', proficiency: 'none', bonuses: [] },
    {
      name: 'Выступление',
      ability: 'charisma',
      proficiency: 'none',
      bonuses: [],
    },
    {
      name: 'Запугивание',
      ability: 'charisma',
      proficiency: 'none',
      bonuses: [],
    },
    {
      name: 'История',
      ability: 'intelligence',
      proficiency: 'none',
      bonuses: [],
    },
    {
      name: 'Ловкость рук',
      ability: 'dexterity',
      proficiency: 'none',
      bonuses: [],
    },
    { name: 'Медицина', ability: 'wisdom', proficiency: 'none', bonuses: [] },
    { name: 'Обман', ability: 'charisma', proficiency: 'none', bonuses: [] },
    {
      name: 'Природа',
      ability: 'intelligence',
      proficiency: 'none',
      bonuses: [],
    },
    {
      name: 'Проницательность',
      ability: 'wisdom',
      proficiency: 'none',
      bonuses: [],
    },
    {
      name: 'Религия',
      ability: 'intelligence',
      proficiency: 'none',
      bonuses: [],
    },
    {
      name: 'Скрытность',
      ability: 'dexterity',
      proficiency: 'none',
      bonuses: [],
    },
    {
      name: 'Убеждение',
      ability: 'charisma',
      proficiency: 'none',
      bonuses: [],
    },
    {
      name: 'Уход за животными',
      ability: 'wisdom',
      proficiency: 'none',
      bonuses: [],
    },
  ],
  health: {
    current: 0,
    max: 0,
    temporary: 0,
    levelGains: [],
    exhaustion: 0,
  },
  hitDice: [],
  extraHitDice: [],
  classResources: [],
  proficiencies: {
    armor: [],
    weapons: [],
    weaponMasteries: [],
    tools: [],
    languages: ['Общий'],
  },
  currency: {
    copper: 0,
    silver: 0,
    electrum: 0,
    gold: 0,
    platinum: 0,
  },
  customCurrencies: [],
  inventory: [],
  notes: [],
  personality: {
    alignment: '',
    age: '',
    height: '',
    weight: '',
    eyes: '',
    hair: '',
    skin: '',
    description: '',
  },
  settings: {
    weaponAttackAbility: null,
    customProficiencyBase: null,
    customProficiencyBonuses: [],
    initiativeAbility: null,
    customInitiativeBase: null,
    customInitiativeBonuses: [],
  },
};
