FROM node:lts-alpine

ARG SERVER_URL
ARG API_SECRET
ARG MAIL_VERIFY_SECRET
ARG MONGODB_URI
ARG API_URL
ARG API_TOKEN
ARG MAIL_HOST
ARG MAIL_USER
ARG MAIL_PASS

ENV SERVER_URL=$SERVER_URL
ENV API_SECRET=$API_SECRET
ENV MAIL_VERIFY_SECRET=$MAIL_VERIFY_SECRET
ENV MONGODB_URI=$MONGODB_URI
ENV API_URL=$API_URL
ENV API_TOKEN=$API_TOKEN
ENV MAIL_HOST=$MAIL_HOST
ENV MAIL_USER=$MAIL_USER
ENV MAIL_PASS=$MAIL_PASS

WORKDIR /opt/app

COPY . ./

RUN npm ci
RUN npm run build

ENTRYPOINT ["node", ".output/server/index.mjs"]
