export {
  PUBLIC_OFFER_ICON,
  PUBLIC_OFFER_INTRO,
  PUBLIC_OFFER_PAGE_DESCRIPTION,
  PUBLIC_OFFER_PAGE_SUBTITLE,
  PUBLIC_OFFER_PAGE_TITLE,
  PUBLIC_OFFER_ROUTE,
  PUBLIC_OFFER_SECTIONS,
  PUBLIC_OFFER_UPDATED_AT,
  PUBLIC_OFFER_UPDATED_PREFIX,
} from './constants';

export {
  SELLER_INN,
  SELLER_NAME,
  SELLER_REQUISITES,
  SELLER_SITE,
  SELLER_STATUS,
} from './requisites';
