export { default as VttgDownloadBuilds } from './VttgDownloadBuilds.vue';
export { default as VttgDownloadModal } from './VttgDownloadModal.vue';
export { default as VttgFaqSection } from './VttgFaqSection.vue';
export { default as VttgFeatureMedia } from './VttgFeatureMedia.vue';
export { default as VttgFeaturesSection } from './VttgFeaturesSection.vue';
export { default as VttgHeroSection } from './VttgHeroSection.vue';
export { default as VttgLanding } from './VttgLanding.vue';
export { default as VttgSectionHeading } from './VttgSectionHeading.vue';
export { default as VttgVideoPlayer } from './VttgVideoPlayer.vue';
