export type { OnlineHeartbeatBody, YandexMetrikaQueue } from './types';

export {
  GOOGLE_ANALYTICS_ID_QUERY_PARAMETER,
  GOOGLE_ANALYTICS_SCRIPT_MARKER,
  HEARTBEAT_COOLDOWN_MS,
  HEARTBEAT_INTERVAL_MS,
  HEARTBEAT_LOCK_NAME,
  HEARTBEAT_URL,
  ONLINE_VISITOR_ID_COOKIE,
  ONLINE_VISITOR_ID_COOKIE_MAX_AGE_SECONDS,
  REGISTERED_ONLINE_TYPE,
  VISITOR_ONLINE_TYPE,
  YANDEX_METRIKA_DESTRUCT_METHOD,
  YANDEX_METRIKA_HIT_METHOD,
  YANDEX_METRIKA_INIT_METHOD,
  YANDEX_METRIKA_INIT_OPTIONS,
  YANDEX_METRIKA_SCRIPT_KEY,
  YANDEX_METRIKA_SCRIPT_URL,
} from './constants';

export { parseOnlineVisitorId } from './schema';
