export {
  USER_AGREEMENT_ICON,
  USER_AGREEMENT_INTRO,
  USER_AGREEMENT_PAGE_DESCRIPTION,
  USER_AGREEMENT_PAGE_SUBTITLE,
  USER_AGREEMENT_PAGE_TITLE,
  USER_AGREEMENT_ROUTE,
  USER_AGREEMENT_SECTIONS,
  USER_AGREEMENT_UPDATED_AT,
  USER_AGREEMENT_UPDATED_PREFIX,
} from './constants';
