export {
  COOKIE_CONSENT_ACCEPT_LABEL,
  COOKIE_CONSENT_CLOSE_LABEL,
  COOKIE_CONSENT_DESCRIPTION,
  COOKIE_CONSENT_DISMISS_KEY,
  COOKIE_CONSENT_KEY,
  COOKIE_CONSENT_MAX_AGE,
  COOKIE_CONSENT_TITLE,
  COOKIE_CONSENT_VERSION,
} from './const';
