export type { CookiePolicyLink, CookiePolicySection } from './types';

export {
  COOKIE_CONSENT_ACCEPT_LABEL,
  COOKIE_CONSENT_CLOSE_ICON,
  COOKIE_CONSENT_CLOSE_LABEL,
  COOKIE_CONSENT_DESCRIPTION,
  COOKIE_CONSENT_DISMISS_KEY,
  COOKIE_CONSENT_ICON,
  COOKIE_CONSENT_KEY,
  COOKIE_CONSENT_MAX_AGE,
  COOKIE_CONSENT_TITLE,
  COOKIE_CONSENT_VERSION,
  COOKIE_POLICY_LINK_ICON,
  COOKIE_POLICY_LINK_LABEL,
  COOKIE_POLICY_ROUTE,
} from './const';

export {
  COOKIE_POLICY_BULLET_ICON,
  COOKIE_POLICY_INTRO,
  COOKIE_POLICY_PAGE_DESCRIPTION,
  COOKIE_POLICY_PAGE_SUBTITLE,
  COOKIE_POLICY_PAGE_TITLE,
  COOKIE_POLICY_SECTIONS,
  COOKIE_POLICY_UPDATED_AT,
  COOKIE_POLICY_UPDATED_DATE_FORMAT,
  COOKIE_POLICY_UPDATED_ICON,
  COOKIE_POLICY_UPDATED_PREFIX,
} from './policy';
