export type { UseCookieNoticeReturn } from './types';

export {
  COOKIE_NOTICE_DESCRIPTION,
  COOKIE_NOTICE_DISMISS_LABEL,
  COOKIE_NOTICE_ICON,
  COOKIE_NOTICE_KEY,
  COOKIE_NOTICE_MAX_AGE,
  COOKIE_NOTICE_TITLE,
  COOKIE_NOTICE_VERSION,
  COOKIE_POLICY_ROUTE,
} from './constants';

export {
  COOKIE_POLICY_INTRO,
  COOKIE_POLICY_PAGE_DESCRIPTION,
  COOKIE_POLICY_PAGE_SUBTITLE,
  COOKIE_POLICY_PAGE_TITLE,
  COOKIE_POLICY_SECTIONS,
  COOKIE_POLICY_UPDATED_AT,
  COOKIE_POLICY_UPDATED_PREFIX,
} from './policy';

export { isCookieNoticeDismissed } from './schema';
