name: Deploy
run-name: Deploy ${{github.ref_name == 'main' && 'Production' || 'Development'}} by @${{ github.actor }}

on:
  push:
    branches:
      - main
      - dev

  workflow_dispatch:

env:
  ENVIRONMENT_NAME: ${{github.ref_name == 'main' && 'prod' || 'dev'}}
  BASE_DOMAIN: ttg.club

concurrency:
  group: deploy-${{github.ref_name}}
  cancel-in-progress: false

jobs:
  env:
    name: Update env
    runs-on: ubuntu-latest
    env:
      CONTAINER_NAME: ttg-next-app-${{github.ref_name == 'main' && 'prod' || 'dev'}}
    outputs:
      CONTAINER_NAME: ${{env.CONTAINER_NAME}}
      NETWORK_NAME: ttg-next-network-${{env.ENVIRONMENT_NAME}}
      IMAGE_NAME: magistrus/${{env.CONTAINER_NAME}}
      BASE_NEXT_DOMAIN: next.${{env.BASE_DOMAIN}}
    steps:
      - run: echo "env is updated"

  ssh:
    name: Update Server
    needs: env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.TMWEB_SSH_HOST}}
          username: ${{secrets.TMWEB_SSH_USER}}
          key: ${{secrets.TMWEB_SSH_KEY}}
          port: ${{secrets.TMWEB_SSH_PORT}}
          script: |
            docker stop ${{needs.env.outputs.CONTAINER_NAME}} && docker rm ${{needs.env.outputs.CONTAINER_NAME}}
            docker run \
              --network ${{needs.env.outputs.NETWORK_NAME}} \
              --ip ${{secrets.DOCKER_APP_CONTAINER_IP}} \
              --name ${{needs.env.outputs.CONTAINER_NAME}} \
              --network-alias ${{secrets.DOCKER_APP_HOST}} \
              --restart on-failure \
              -it $(docker build -q .)
              -e SERVER_URL=https://app.${{needs.env.outputs.BASE_NEXT_DOMAIN}}
              -e API_SECRET=${{secrets.API_SECRET}}
              -e MAIL_VERIFY_SECRET=${{secrets.MAIL_VERIFY_SECRET}}
              -e MONGODB_URI=mongodb://${{secrets.DOCKER_MONGO_USER}}:${{secrets.DOCKER_MONGO_PASSWORD}}@${{secrets.DOCKER_MONGO_HOST}}:27017/${{secrets.DOCKER_MONGO_DB}}?authSource=${{secrets.DOCKER_MONGO_DB}}
              -e API_URL=//${{secrets.DOCKER_API_HOST}}
              -e API_TOKEN=${{secrets.API_TOKEN}}
              -e MAIL_HOST=smtp.mail.ru
              -e MAIL_USER=support@ttg.club
              -e MAIL_PASS=${{secrets.EMAIL_PASSWORD}}
            docker rmi $(docker images --filter "dangling=true" -q --no-trunc) &
