name: PR Check

on:
  pull_request:
    branches:
      - main
      - dev

    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - review_requested
      - auto_merge_enabled

permissions:
  actions: read
  contents: read
  security-events: write

concurrency:
  group: pr-check-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  analyze:
    name: Analyze PR
    if: ${{ !github.event.pull_request.draft }}
    uses: ./.github/workflows/codeql.yml

  build:
   name: Code Check PR
   if: ${{ !github.event.pull_request.draft }}
   uses: ./.github/workflows/code-check.yml
